04 auth
Mr-Foxx/nodejs-homework-rest-api pull request #3
Opened 2023-08-02 06:44 UTC by Mr-Foxx

looks like done

2023-08-02 10:19 UTC, ceREAL133 requested changes

2023-08-02 10:19 UTC, ceREAL133 commented on routes/api/contacts-routes.js
> +    const { _id: owner } = req.user;
all of this functions should be saparated in different file, called controller

2023-08-02 10:19 UTC, ceREAL133 commented on routes/api/auth-router.js
> +  const { email, password } = req.body;
all of this functions should be saparated in different file, called controller

2023-08-04 14:17 UTC, Mr-Foxx commented
I corrected the comments

2023-08-05 12:54 UTC, ceREAL133 approved these changes

2023-08-05 13:06 UTC, merged